const STORAGE_ACCOUNT_NAME = process.env["STORAGE_ACCOUNT_NAME"];
const STORAGE_ACCOUNT_KEY = process.env["STORAGE_ACCOUNT_KEY"];
const STORAGE_CONTAINER_NAME = process.env["STORAGE_CONTAINER_NAME"];
const YOUTUBE_KEY = "AIzaSyAdV-TwUoaTKb0OFU8HVw7eMuvPpVW-6HI";

module.exports = {
    STORAGE_ACCOUNT_NAME,
    STORAGE_ACCOUNT_KEY,
    STORAGE_CONTAINER_NAME,
    YOUTUBE_KEY
};